# Generated by Django 4.2.3 on 2023-10-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_manager_app", "0013_savinggoal_currency"),
        ("incomes", "0002_alter_income_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "income"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget_manager_app.category",
            ),
        ),
    ]
