# Generated by Django 5.0 on 2023-12-21 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helper_models", "0004_alter_tag_user"),
        ("incomes", "0004_alter_income_options_alter_income_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="category",
            field=models.ForeignKey(
                limit_choices_to={"type": "income"},
                on_delete=django.db.models.deletion.CASCADE,
                to="helper_models.category",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="currency",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="helper_models.currency"),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="income",
            name="tags",
            field=models.ManyToManyField(blank=True, to="helper_models.tag"),
        ),
    ]
