# Generated by Django 4.2.3 on 2023-10-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget_manager_app", "0013_savinggoal_currency"),
        ("expenses", "0002_alter_expense_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "expense"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget_manager_app.category",
            ),
        ),
    ]
