# Generated by Django 4.2.3 on 2023-08-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager_app', '0003_alter_expense_category_alter_expense_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
