# Generated by Django 4.2.3 on 2023-09-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager_app', '0005_alter_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(max_length=64),
        ),
    ]
