# Generated by Django 4.2.3 on 2023-09-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_manager_app', '0006_alter_expense_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
    ]
