# Generated by Django 4.2.3 on 2023-10-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_manager_app", "0007_remove_expense_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("is_income", models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name="expense",
            name="category",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="user",
        ),
        migrations.RemoveField(
            model_name="income",
            name="category",
        ),
        migrations.RemoveField(
            model_name="income",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="income",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="income",
            name="user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="CategoryExpense",
        ),
        migrations.DeleteModel(
            name="CategoryIncome",
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.DeleteModel(
            name="Income",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
