# Generated by Django 4.2.3 on 2023-10-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_manager_app", "0008_category_remove_expense_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="non_deletable",
            field=models.BooleanField(default=False),
        ),
    ]
