# Generated by Django 4.2.3 on 2023-10-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_manager_app", "0010_rename_non_deletable_category_non_editable"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("amount", models.FloatField()),
                ("goal", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_income",
        ),
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")], default=None
            ),
            preserve_default=False,
        ),
    ]
