# Generated by Django 4.2.3 on 2023-10-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget_manager_app", "0012_alter_category_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="savinggoal",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget_manager_app.currency",
            ),
            preserve_default=False,
        ),
    ]
