# Generated by Django 4.2.6 on 2023-11-02 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helper_models", "0001_initial"),
        ("incomes", "0004_alter_income_options_alter_income_category_and_more"),
        ("expenses", "0004_alter_expense_options_alter_expense_category_and_more"),
        ("budget_manager_app", "0014_alter_savinggoal_amount_alter_savinggoal_goal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AlterField(
            model_name="savinggoal",
            name="currency",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="helper_models.currency"),
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
    ]
