# Generated by Django 4.2.6 on 2023-11-02 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incomes', '0004_alter_income_options_alter_income_category_and_more'),
        ('expenses', '0004_alter_expense_options_alter_expense_category_and_more'),
        ('budget_manager_app', '0015_delete_category_delete_tag_alter_savinggoal_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savinggoal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('expenses', models.ManyToManyField(to='expenses.expense')),
                ('incomes', models.ManyToManyField(to='incomes.income')),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Users with whom the budget is shared', related_name='shared_budgets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who owns the budget', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
