# Generated by Django 4.2.6 on 2023-11-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_manager_app", "0016_alter_savinggoal_amount_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="goals",
            field=models.ManyToManyField(to="budget_manager_app.savinggoal"),
        ),
    ]
