# Generated by Django 4.2.6 on 2023-11-07 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_manager_app', '0018_budget_currency_alter_budget_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='savinggoal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
