# Generated by Django 4.2.6 on 2023-11-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "budget_manager_app",
            "0020_remove_savinggoal_currency_remove_savinggoal_user",
        ),
        ("saving_goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="goals",
            field=models.ManyToManyField(blank=True, to="saving_goals.savinggoal"),
        ),
        migrations.DeleteModel(
            name="SavingGoal",
        ),
    ]
